### ISSUE TITLE
How to create a client on windows

### ISSUE THREAD

**Issue by Bruce-Cui** [cakeMP/cakeMP#2]
I have built a StrawberryPie.asi on vs2017 and put it in the Grand Theft Auto V folder. But the client didn't started, i modified the NetworkManager::Initialize() function, then i found the variable m_localHost is null.How to solve the problem? thank you very much

**Comment by codecat** [comment]
Is there anything in your logfiles? You might need to create a `StrawberryPie.ini` file:

https://github.com/codecat/quinMP/blob/cabeb58a68e2094a403358d9c418311ecfc3be62/StrawberryPie/System/Settings.cpp#L39-L44

If `m_localHost` is null, that could mean that ENet failed to initialize. (Which it would show in the logfile, too.)

**Comment by Bruce-Cui** [comment]
I just created a Strawberry.ini file, and it can be read.
but the client still can't be created. because m_localHost is null.Here's the log. 
`    Strawberry Pie starting at 2017/08/25

[18:38:54] Initializing v0.1.000.000
[18:38:54] Settings: Connect to host: 127.0.0.1
[18:38:54] Settings: Connect to port: 5678
[18:38:54] Settings: Nickname: 'bruce_cui'
[18:39:51] Game scripts unloaded.
[18:39:51] Client initializing.
[18:39:51] Resolution: 1280 x 800
[18:39:51] Failed to create m_localHost!`

enet_initialize() is ok, or the NetworkManager::Initialize() function would return , so I don't known why the function enet_host_create(nullptr, 1, 1, 0, 0) return a null value.

**Comment by codecat** [comment]
Which version of GTA 5 is this, by the way? It might be a problem with the latest build and the winsock initialization, I've had problems with that in the past.

In which case, you can try reproducing it by enabling the SHV developer mode (see the SHV readme), and reloading the asi as soon as the game starts and checking if it loads it, then.

You can see the cases in which `enet_host_create` returns null, here:

https://github.com/lsalzman/enet/blob/f46fee0acc8e243b2b6910b09693f93c3aad775f/host.c#L29

**Comment by codecat** [comment]
Also, if that doesn't work, I included a prebuilt ENet library, perhaps it would be better to build ENet from source (using the latest version, I suppose).

**Comment by Bruce-Cui** [comment]
GTA 5's version is 1.35. I can create a client in my demo using the same code,and it works, but it doesn't work on GTA5.  I dubuged the source code of ENet, and found the error_code is 258.
ENetSocket
enet_socket_createC(ENetSocketType type, int *error_code)
{
	SOCKET listener = socket(PF_INET, type == ENET_SOCKET_TYPE_DATAGRAM ? SOCK_DGRAM : SOCK_STREAM, 0);
	if (listener == INVALID_SOCKET)
	{
		*error_code= WSAGetLastError();
	}
	return listener;
}

**Comment by codecat** [comment]
Uh, I can't find 258 on the [Windows Sockets Error Codes](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx) page. :/

Have you tried the reloading thing yet? It might just work. If it works, there's a few ways to workaround the problem.
